apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cham3lyon/k8s-project.git
    targetRevision: HEAD
    path: manifests/my-sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
