apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  sources: []
  project: default
  namespace: ''
  cluster-scoped: true
  acme:
    email: adm.leonwalther@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-key
    solvers:
      - dns01:
          cloudflare:
            email: adm.leonwalther@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
